[tool.poetry]
authors = ["Didier SCHMITT <dschmitt@equancy.com>"]
description = "Datalake Framework"
license = "MIT"
name = "datalake-framework"
packages = [
  {include = "datalake"},
]
repository = "https://git.equancy.cloud/equancy/data-technologies/datalake-framework"
version = "0.0.0"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.26.0"
google-cloud-storage = "^1.42.3"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
flake9 = "^3.8.3"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.flake8]
ignore = "E501,W503"
